version: 2.1

jobs:  
  build_osx:
    macos:
      xcode: 12.5.1 # indicate your selected version of Xcode
    steps:
      - checkout
      - run: make clang
  build_linux_gcc:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: make gcc

workflows:
  version: 2

  INF473X_workflow:
    jobs:
      - build_osx
      - build_linux